#
#  Copyright 2022 Davide Bettio <davide@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: ESP32 Build

on: [push, pull_request]

jobs:
  esp32-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: "APT update"
      run: sudo apt update -y

    - name: "Install deps"
      run: sudo apt install -y ninja-build libgcrypt20-dev libglib2.0-dev libpixman-1-dev libpixman-1-dev

    - name: "PIP install"
      run: pip install pytest-embedded

    - name: "Build QEMU"
      run: |
        git clone https://github.com/espressif/qemu.git

        cd qemu

        ./configure --target-list=xtensa-softmmu \
        --enable-gcrypt \
        --enable-debug --enable-sanitizers \
        --disable-strip --disable-user \
        --disable-capstone --disable-vnc \
        --disable-sdl --disable-gtk

        ninja -C build



    - name: "Build: customized esp-idf container"
      run: docker build -t atomvm/ci-idf:v3.3.2 -f esp32-dockerfile .
      working-directory: .github/workflows

    - name: "Build: AtomVM (ESP32 platform)"
      run: docker run --rm -v $PWD:/atomvm -w /atomvm atomvm/ci-idf:v3.3.2 src/platforms/esp32
